# This file was generated by GoReleaser. DO NOT EDIT.
cask "self-host" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "4d5ca257d9825a558e52f57caa5f7a2ebb601822f8dcf09a972ec0f754ace970"
      url "https://github.com/momoi-labs/self-host/releases/download/v#{version}/self-host_v#{version}_aarch64-apple-darwin.tar.gz"
    end
    on_intel do
      sha256 "187c0fbf782398bd3f93cad358a4124b6713ebcb50006c0d354cad6e7948e908"
      url "https://github.com/momoi-labs/self-host/releases/download/v#{version}/self-host_v#{version}_x86_64-apple-darwin.tar.gz"
    end
  end

  name "self-host"
  desc "Publish applications on your own LAN"
  homepage "https://github.com/momoi-labs/self-host"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "self-host"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/self-host"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    This package installs the binary only. It does not configure Docker,
    DNS, or a launchd daemon. See the repository README for Host setup.
  EOS
end
