# This file was generated by GoReleaser. DO NOT EDIT.
cask "self-host" do
  version "0.4.1"

  on_macos do
    on_arm do
      sha256 "edaef0205f11314a546390e7b4419ce9416d7212e3c919dd46409b50668af7df"
      url "https://github.com/momoi-labs/self-host/releases/download/v#{version}/self-host_v#{version}_aarch64-apple-darwin.tar.gz"
    end
    on_intel do
      sha256 "8cc91d8be01b807e181e4015b165aa3140d19220e6095f2abd22fcf136624971"
      url "https://github.com/momoi-labs/self-host/releases/download/v#{version}/self-host_v#{version}_x86_64-apple-darwin.tar.gz"
    end
  end

  name "self-host"
  desc "Publish applications on your own LAN"
  homepage "https://github.com/momoi-labs/self-host"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "self-host"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/self-host"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    This package installs the binary only. It does not configure Docker,
    DNS, or a launchd daemon. See the repository README for Host setup.
  EOS
end
