# This file was generated by GoReleaser. DO NOT EDIT.
cask "self-host" do
  version "0.7.0"

  on_macos do
    on_arm do
      sha256 "cbabaa32cfd6bd9129b3f132976134f32da770c197635422d7839c9f3f737b59"
      url "https://github.com/momoi-labs/self-host/releases/download/v#{version}/self-host_v#{version}_aarch64-apple-darwin.tar.gz"
    end
    on_intel do
      sha256 "b8e62cd2db5deecf0d6b37b2b186799cd6fe1daf0e5e399ecf43e148655c5e71"
      url "https://github.com/momoi-labs/self-host/releases/download/v#{version}/self-host_v#{version}_x86_64-apple-darwin.tar.gz"
    end
  end

  name "self-host"
  desc "Publish applications on your own LAN"
  homepage "https://github.com/momoi-labs/self-host"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "self-host"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/self-host"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    This package installs the binary only. It does not configure Docker,
    DNS, or a launchd daemon. See the repository README for Host setup.
  EOS
end
